# Generated by Django 6.0.4 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('frog', 'Frog')], max_length=20)),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('svg_path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['pet_type', 'level'],
                'unique_together': {('pet_type', 'level')},
            },
        ),
    ]
