# Generated by Django 6.0.4 on 2026-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['pet_type', 'level', 'mood']},
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pet',
            name='mood',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('focused', 'Focused'), ('happy', 'Happy'), ('tired', 'Tired')], default='neutral', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('pet_type', 'level', 'mood')},
        ),
    ]
