# Generated by Django 6.0.4 on 2026-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_current_pet_userprofile_pet_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pet_mood',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('focused', 'Focused'), ('happy', 'Happy'), ('tired', 'Tired')], default='neutral', max_length=20),
        ),
    ]
